### ISSUE TITLE
Since v6.0.0 fails to build for wasm32-unknown-unknown

### ISSUE THREAD

**Issue by bast** [sdd/kiddo#515]
First of all thank you for developing this library!

Since v6.0.0 I can no longer build for wasm32-unknown-unknown. This worked fine with v5.

How to reproduce the problem:
```
cargo new example
cd example
cargo add kiddo@6.0.0
cargo check --target wasm32-unknown-unknown
```

Compilation fails with:
```
  error[E0432]: unresolved import `crate::stem_strategy::prefetch::prefetch_t1`
    --> src/stem_strategy/donnelly/core.rs:1:5
  error[E0432]: unresolved imports `crate::stem_strategy::prefetch::prefetch_t0`, `crate::stem_strategy::prefetch::prefetch_t1`
    --> src/stem_strategy/eytzinger/mod.rs:29:38
  error[E0425]: cannot find value `BYTES_PER_LINE` in this scope
    --> src/stem_strategy/donnelly/core.rs:540:49
```

If this wasn't intentional, it might be relatively easy to solve by gating by architecture.

I can patch this for my projects by forking but maybe you would prefer this to be fixed in the main line? I could possibly help patching it although I am not an expert in this.

**Comment by sdd** [comment]
Hi! No, this was not intentional - thanks for reporting. I will ensure that `wasm32-unknown-unknown` is added as a specific target in CI so that a regression like this doesn't happen again, and so that I can be sure it works when I have a fix.

**Comment by sdd** [comment]
[Fixed!](https://github.com/sdd-org/kiddo/pull/516) Issue was the lack of a processor-specific prefetch instruction on wasm32.

I added a required CI check to ensure we can build to WASM to ensure we don't get another regression again.

Will publish as 6.0.1

**Comment by bast** [comment]
Thank you so much for the fix!

**Comment by sdd** [comment]
No problem! https://crates.io/crates/kiddo/6.0.1 just got published 👍 

Would love to hear how you're finding v6 (once it is working for you 😅) if you're upgrading from v5.

**Comment by bast** [comment]
Thank you! I will give feedback after the upgrade. It's an extremely useful library.

**Comment by bast** [comment]
It works very well after the upgrade from v5 to v6 - I use it for nearest neighbor searches in 2D within the context of computational oceanography.

**Comment by sdd** [comment]
Great, glad to hear it's working well and that you're putting it to good use! 😊
